version: '3.3'

services:
  friendsurance:
    image: maven:3.3-jdk-8
    volumes:
      - .:/app
    working_dir: /app
    command: mvn clean test
  chrome-dirver:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm